load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "libsbp",
    srcs = [],
    hdrs = [
    	"acquisition.h",
	"bootload.h",
	"common.h",
	"edc.h",
	"ext_events.h",
	"file_io.h",
	"flash.h",
	"gnss.h",
	"imu.h",
	"logging.h",
	"mag.h",
	"navigation.h",
	"ndb.h",
	"observation.h",
	"orientation.h",
	"piksi.h",
	"sbas.h",
	"sbp.h",
	"settings.h",
	"ssr.h",
	"system.h",
	"tracking.h",
	"user.h",
	"vehicle.h",
	"version.h",
    ],
    deps = [],
)

cpplint()
