package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "heading_gnss_cc_proto",
    deps = [
        ":heading_gnss_proto",
    ],
)

proto_library(
    name = "heading_gnss_proto",
    srcs = [
        "headingGnss.proto",
    ],
)
