package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "fake_gps_cc_proto",
    deps = [
        ":fakeGps_proto",
    ],
)

proto_library(
    name = "fakeGps_proto",
    srcs = [
        "fakeGps.proto",
    ],
)
