package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "wheel_odometry_cc_proto",
    deps = [
        ":wheelOdometry_proto",
    ],
)

proto_library(
    name = "wheelOdometry_proto",
    srcs = [
        "wheelOdometry.proto",
    ],
)
