load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "TCPClient",
    srcs = ["TCPClient.cpp"],
    hdrs = [
    "TCPClient.h"
    ],
    deps = [],
)

cpplint()
