package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "visual_odometry_cc_proto",
    deps = [
        ":visualOdometry_proto",
    ],
)

proto_library(
    name = "visualOdometry_proto",
    srcs = [
        "visualOdometry.proto",
    ],
)
