package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "april_tags_cc_proto",
    deps = [
        ":april_tags_proto",
    ],
)

proto_library(
    name = "april_tags_proto",
    srcs = [
        "aprilTags.proto",
    ],
)
